title: "PINNs para Ajuste de Curvas de Crecimiento en Kéfir con Ultrasonido"
language: es
logo: images/mcd_logo.png

repository:
  url: https://github.com/fdcir3tt/kefir_ajuste
  branch: gh-pages
  path_to_book: book

execute:
  execute_notebooks: "off"

html:
  favicon: images/mcd_logo.png
  use_repository_button: true
  hide_footer_links: true
  folders: true

# Bibliografía
bibtex_bibfiles:
  - referencias.bib
  
latex:
  extra_metadata:
      citation-style: apa
      pandoc-citeproc: true
  mathjax: true

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
  config:
    add_module_names: False
    bibtex_reference_style: author_year
    bibtex_default_style: unsrt
    autodoc_default_options:
      members: true
      undoc-members: true
      show-inheritance: true
    confoverrides:
      sys_path:
        - "/Users/federicocirett/Documents/GitHub/kefir_ajuste_book/src/kefir_ajuste/src"
        - "/Users/federicocirett/Documents/GitHub/kefir_ajuste_book/src/kefir_ajuste/scripts"